<?php
/**
 * @name         Preparedness Assesment (PA)
 * @version      01
 * @package      pa
 * @author       Ramindu Deshapriya <rdeshapriya@virtusa.com>
 * @about        Developed in whole or part by the U.S. National Library of Medicine,the Sahana Foundation and Virtusa Corporation
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @link		 http://www.virtusa.com
 * @license	 	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2013.11.21
 */


$conf['mod_pa_name']         = _t("Preparedness Assesment");   // Defines the name of the module
$conf['mod_pa_menuorder']    =  22;                             	// Defines this module's main menu priority
$conf['mod_pa_dependencies'] = "";
$conf['mod_pa_version']      = 24;
