<?php
/**
 * @name         Geographic Information System
 * @version      01
 * @package      gis
 * @author       Milindu Sanoj Kumarage <agentmilindu@gmail.com>
 * @about        Developed in whole or part by the U.S. National Library of Medicine, the Sahana Foundation.
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @link		 http://www.agentmilindu.com
 * @license	 	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2014.06.07
 */


$conf['mod_gis_name']         = _t("Geographic Information System");   // Defines the name of the module
$conf['mod_gis_menuorder']    =  23;                             	// Defines this module's main menu priority
$conf['mod_gis_dependencies'] = "";
$conf['mod_gis_version']      = 01;
