<?php
/**
 * @name         Patient Monitoring
 * @version      1.0
 * @package      mon
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @author		 Ramindu Deshapriya <rdeshapriya@virtusa.com>
 * @about        Developed in whole or part by the U.S. National Library of Medicine, Virtusa Corporation and the Sahana Foundation
 * @link         https://pl.nlm.nih.gov/about
 * @link		 http://virtusa.com
 * @link         http://sahanafoundation.org
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2013.0418
 */


$conf['mod_mon_name']         = _t("Patient Monitoring");   // Defines the name of the module
$conf['mod_mon_menuorder']    =  10;                            // Defines this module's main menu priority
$conf['mod_mon_dependencies'] = "";
$conf['mod_mon_version']      = 1;
