<?php
/**
 * @name         Focal Point Administration
 * @version      01
 * @package      fpa
 * @author       Thilina Mendis <thilina.mendi@gmail.com>
 * @about        Developed in whole or part by the U.S. National Library of Medicine,the Sahana Foundation and Virtusa Corporation
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @link		 http://www.virtusa.com
 * @license	 	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2013.11.21
 */


$conf['mod_fpa_name']         = _t("Focal Point Administration");   // Defines the name of the module
$conf['mod_fpa_menuorder']    =  75;                             	// Defines this module's main menu priority
$conf['mod_fpa_dependencies'] = "";
$conf['mod_fpa_version']      = 23;
